Logging:
    default: INFO

General:
    Modus:          Afterburner
    End_Time:       0.0
    Randomseed:     -1
    Nevents:        100      # Number of (sampler + smash) events
    SamplerType:    MSU      # options so far: Microcanonical, MSU, iSS

Output_Directory:  smash_output_MSU
Output:
    Output_Interval: 10.0
    Particles:
        Only_Final: True
        Format:     ["Oscar2013", "Binary"]
        Extended:   True

# Both SMASH and microcanonical sampler are set up from these
Particles:   "../external_codes/smash/input/particles.txt"
DecayModes:  "../external_codes/smash/input/decaymodes.txt"

MicrocanonicalSampler:
    HyperSurface:   "results/surface.dat"
    MaxMass:        2.5    # Maximal mass of hadrons to be sampled [GeV]

MSUSampler:
    RESONANCES_INFO_FILE:   "../external_codes/best_sampler/software/resinfo/pdg-SMASH.dat"
    RESONANCES_DECAYS_FILE: "../external_codes/best_sampler/software/resinfo/pdg-SMASH.dat"
    HYPER_INFO_FILE:        "results/surface.dat"
    SAMPLER_SFDIRNAME:      "../external_codes/best_sampler/software/resinfo/spectralfunctions"
    SAMPLER_TFMIN: 0.110
    SAMPLER_TFMAX: 0.170
    SAMPLER_NTF: 60
    SAMPLER_SIGMAFMIN: 0.093
    SAMPLER_SIGMAFMAX: 0.093
    SAMPLER_NSIGMAF: 1
    SAMPLER_SETMU0: false
    SAMPLER_BOSE_CORR: true
    SAMPLER_N_BOSE_CORR: 5
    SAMPLER_USE_POLE_MASS: true

iSS:
    iSS_INPUTFILE: "../external_codes/iSS/iSS_parameters.dat"
    WORKING_PATH: "./results"
    HYDRO_MODE: 2
    INCLUDE_DELTAF_SHEAR: 0
    INCLUDE_DELTAF_BULK:  0
    INCLUDE_DELTAF_DIFF:  0
    RESTRICT_DELTAF: 0

