Logging:
    default: INFO

General:
    Modus:          Afterburner
    End_Time:       100.0
    Randomseed:     -1
    Nevents:        100      # Number of (sampler + smash) events

Output_Directory:  smash_output_MSU
Output:
    Output_Interval: 10.0
    Particles:
        Only_Final: True
        Format:     ["Oscar2013", "Binary"]
        Extended:   True

# Both SMASH samplers are set up from these
Particles:   "../external_codes/smash/input/particles.txt"
DecayModes:  "../external_codes/smash/input/decaymodes.txt"

HyperSurface:   "results/surface.dat"

Sampler:
    Type: iSS   # options so far: Microcanonical, MSU, iSS
    ViscousCorections:
        Shear:     True
        Bulk:      True
        Diffusion: True
    QuantumCorrections:    True
    SpectralFunctions:     True

    # Additional sampler-specific options
    Microcanonical: 
        PatchEnergy:   20.0  # GeV
