#!/usr/bin/env bash

# This script download a sample 3D hydrodynamic hypersurface generated by MUSIC
# This surface file is from a event-averaged simulation for 0-10% AuAu @ 19.6 GeV
# Reference: Phys.Rev.C 102 (2020) 1, 014909; e-Print: 2003.05852 [nucl-th]

mkdir -p results
(
    cd results
    wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1hQKzm9d52HB3JXD5Z_fvvOYNaj91nLFy' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1hQKzm9d52HB3JXD5Z_fvvOYNaj91nLFy" -O surface.dat

    rm -rf /tmp/cookies.txt

    wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=16hZXFRC6HVhXSLluR8trNfsSgnu4CCjZ' -O music_input

    echo "This surface file is for 0-10% AuAu @ 19.6 GeV" > README
    echo "Reference: Phys.Rev.C 102 (2020) 1, 014909; e-Print: 2003.05852 [nucl-th]" >> README
)
