Logging:
    default: INFO

General:
    Modus:          Afterburner
    End_Time:       200.0
    Randomseed:     -1
    Nevents:        1

Output:
    Output_Interval: 10.0
    Particles:
        Format:          ["Oscar2013"]
