Logging:
    default: INFO

General:
    Modus:          Afterburner
    End_Time:       100.0
    Randomseed:     -1
    Nevents:        100      # Number of (sampler + smash) events

Output_Directory:  smash_output_MSU
Output:
    Output_Interval: 10.0
    Particles:
        Only_Final: Yes
        Format:     ["Oscar2013", "Binary"]
        Extended:   True

# Both SMASH and samplers are set up from these
Particles:   "../external_codes/smash/input/particles.txt"
DecayModes:  "../external_codes/smash/input/decaymodes.txt"

# The same folder must contain music_input file for iSS sampler
HyperSurface:   "results/surface.dat"

Sampler:
    Type: MSU   # options so far: Microcanonical, MSU, iSS
    ViscousCorections:
        Shear:     False
        Bulk:      False
        Diffusion: False
    QuantumCorrections:    False
    SpectralFunctions:     False

    # Additional sampler-specific options
    Microcanonical: 
        PatchEnergy:   50.0  # GeV
